# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af83f66007399d2de7e20bdd10bd6d909f6bfe8716b4ec608361e9c27d5bca2634b7d3d6d5de570afe90c425bc8396c9f779ca0e7ce78d5b3c401a3fffe077e5

test:
  secret_key_base: f49d19c6627760555f64cdc1a2798087853ffca72f640abd9c1f7fad32a9b0ffeeb7710adc130b006d93e68bec6e2f36e6336c11d630a700986f42afbdc514e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
